/**
 * @enum {number}
 */
export const MessageTokens = {
    unsavedChanges: 0,
    removeLevel:1,
    loadLevel:2,
    turnOnBuilder:3,
    swapDesign:4,
    obstacles:5,
    startPosition: 6,
    targetPosition: 7,
    tool: 8,
    language: 9,
    height: 10,
    width: 11,
    slow: 12,
    normal: 13,
    fast: 14,
    superFast: 15,
    numberOfFunctionCalls: 16,
    save: 17,
    clear: 18,
    stop: 19,
    defaultMapName: 20,
    nameLabel: 21,
    levelNamePlaceholder: 22,
    gridGradient: 23,
    enable: 24,
    preset: 25,
    from: 26,
    mid: 27,
    midPosition: 28,
    to: 29,
    angle: 30,
    obstacleColor: 31,
    obstacleBorder: 32,
    clearObstacles: 33,
    copy: 34,
    record: 35,
    sound: 36,
    start: 37,
    reset: 38,
    goLabel: 39,
    leftLabel: 40,
    rightLabel: 41,
    viewOnGithub: 42,
    day: 43,
    night: 44,
    deleteLevelConfirmation: 45,
    fill: 46,
    border: 47,
    copyCode: 48,
    downloadCode: 49,
    uploadCode: 50,
};